spring.application.name=secondHandTa

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=second_hand_trading;encrypt=false;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=123

#SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# MyBatis
mybatis.configuration.map-underscore-to-camel-case=true
pagehelper.helperDialect=sqlserver
pagehelper.reasonable=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB